### ISSUE TITLE
Reviewers' comments related to the Introduction

### ISSUE THREAD

**Issue by Dewi-Amaliah** [numbats/yowie-paper#2]
Some points and questions made by the reviewers regarding this issue are:

1. How is this manuscript relevant for teachers and/or students in statistics and data science?
2. A revision would require significant reframing so that readers can help their students to experience the journal from wild to textbook data.
3. The discussion of the difference between open data and wild data reminded the reviewer of Jer Thorp’s essay “Open for who?” https://medium.com/memo-random/open-for-who-ce698a8de79c You may find it interesting.
4. The authors prominently cite (Chatfield 1985) for the definition of the term “IDA”. However, Chatfield fairly explicitly defines IDA to be a data summarizing and scrutinizing process; not a cleaning, scrubbing, or munging process. It seems curious to me that the whole paper is framed as being “IDA” based on the author’s unsupported statement that data cleaning should be considered part of IDA. 
5. The authors also emphasize that “There are few research papers that document the data cleaning”. While I agree that data cleaning is under-emphasized and under-documented, it’s hardly true that there are no papers on the topic. A quick Google Scholar search for “data cleaning” unearths many scholarly papers and books on the principles of this process, none of which appear to be cited in this work. 
6. Where is IDA undervalued and neglected? Research? Teaching? Both?
7. The authors discuss refreshing an example from Singer and Willet (2003), but this isn’t ever completed. They compare the data, but not the longitudinal model. Again, it’s more about demonstrating a procedure for “initial data analysis” than it is reproducing Singer and Willet (2003). 
8. Tidy and tame data are discussed in passing and the utility of tidy and tame data is not obvious. The authors later describe tidy data rather clearly (page 7) but tame data never receives the same treatment. 
9. More discussion about the textbook selected as the exemplar is needed. It sounds like this dataset is used in many books, why choose that one? The text should include the name of the book, so readers do not need to flip to the citations in order to learn what it was. From the name, I am guessing that the book focuses heavily on this dataset, which is why it makes sense to reproduce their subset. Be explicit about this.

**Comment by emitanaka** [comment]
Point 1 in #4 should be addressed in the intro: 

"to find the anomaly in the wages values" This comes as a surprise to the reader. What anomaly? The wage anomalies should be mentioned in the introduction so as not to be a surprise at this point in the manuscript.

**Comment by dicook** [comment]
The intro has "IDA to find and repair anomalies" in the outline of the paper. 

Changing the wording where we say "In addition, we also aim to find the anomaly in the wages values using this approach." around line 308 would be better. Anomaly has become a field of its own, of finding outliers. We simply want to express that we anticipate finding problems in the data, and will need to work out how to fix them, in the IDA stage.
