### ISSUE TITLE
Dataset and variables-related comments

### ISSUE THREAD

**Issue by Dewi-Amaliah** [numbats/yowie-paper#3]
These are the reviewers' comments related to the dataset and data cleaning process: 

1. A historical context of NLSY79 would be helpful. Specifically, the dropped subjects are mentioned but there’s no context of why. By the argument of the paper, these steps should be transparent and well-considered.
2. The discussion around the highest grade completed is mechanical in what was done but lacks substantive reasoning for those decisions and possible downstream consequences. 
3. It is not clear why participants without a high school degree are not part of the analysis. 
4. Please clarify. "If either the hourly wage or hours worked is missing, we do not tally this." I take "this" to mean "number_of_jobs". But in row 2, total_hours is missing, yet number_of_jobs is 1. The number of jobs (1) was tallied even though hours worked were missing.
5. What does “yearly mean hourly wages with years of workforce experience” mean? Is that one variable or two? 
6. Was your goal to collect data from 1994-2018 or 1979-2018? Page 4 states 1994 onward, but from the figures later it appears that you collected data starting in 1979 (which makes more sense to me).
7. I was confused by the following section: “We choose to use this revised May data because it seemed to have less missing and presumably has been checked. However, there is no revised May data for 2012, 2014, 2016, and 2018, thus, we use the ordinary May data for these years.” I was assuming the data was collected on a yearly basis, but this section suggests it was collected each month. Please clarify somewhere in the paper. 
8. The authors explain the complication of the “years of job experience” variable being unavailable in the raw data. This information is available in the NLSY79 data accessor; it seems to simply have been not selected in the initial data download by the authors. Given that the stated goal is to recreate the textbook data, this seems like a glaring oversight. 
9. What is dplyr used for? Are there tidyverse packages used but not mentioned? If not, splitting this sentence into two may make it clearer which package is used for what purpose. Also, I haven't tried it in code, but I imagine that the data could be tidied as described just using pivot_longer, at least for the job number, year, and wage data. In other words, I don't see why dplyr or stringr would be needed for the data described on page 6.
10. The author switches between gender (man/woman/etc) and sex (male/female/etc.) throughout the manuscript. Further, the explanation here covers important ideas in teaching how to use data on gender/sex and race, but it’s just the beginning of ideas. It might be better to discuss the questions on the survey and discuss possible shortcomings, rather than make a somewhat empty gesture towards today’s standard. 
11. I don't know that Table 1 is necessary as I don't have anything to compare it to. If the numbers check out, a simple statement to that effect would suffice. 
12. Table 2 seems to have more precision than is necessary. Certainly 100% does not need to be reported as 100.00%, and probably all the percentages could be rounded to the nearest 1 percent. The caption could explain this, as there might be some rounding errors. 
13. Figure 2’s caption should include something about how that data is the raw values from the survey, before imputing anomalous values so the figure and caption can stand alone. 
14. Need more explanation for Figure 3, i.e., there is a narrative step missing here, which is that looking at those samples led you to look at plots that show values for the wage variable over all participants and all years. The phrase “the summary plots” was not enough description for me to know what to expect when I flipped to Figure 3. Please be explicit about what the three plots were, why they were made, and what you were looking for. I think there is another narrative step missing about Figure 3C, which is that after you saw there were outliers you tried to identify which respondents had the extreme values. Again, please spell this out in the text. When you return to the plots for the entire dataset in Figure 5, please make parallel comments. 
15. The authors explain the complication of the “years of job experience” variable being unavailable in the raw data. This information is available in the NLSY79 data accessor; it seems to simply have been not selected in the initial data download by the authors. Given that the stated goal is to recreate the textbook data, this seems like a glaring oversight.

**Comment by emitanaka** [comment]
We need to update Figure 1 if adding the new experience variable @Dewi-Amaliah

**Comment by Dewi-Amaliah** [comment]
Hi @emitanaka, I have updated Figure 1.
