### ISSUE TITLE
blinding issue

### ISSUE THREAD

**Issue by emitanaka** [numbats/yowie-paper#7]
I'm putting this as an issue instead of edits since I think the merge conflict undid my edits.

How necessary is the latter part of the sentence? In particular, we need to adhere to blinding so I removed "supervised by author Cook" out to adhere to this. 

"The wages data was used to illustrate exploratory longitudinal data analysis in Ozlem Ilk's PhD thesis supervised by author Cook [@ilk2004]"

**Comment by dicook** [comment]
that should have been removed. i agreed with the changes you made, and though it had been checked in appropriately. i can check the git logs to see what happened.

> On 14 Feb 2022, at 10:54 am, Emi Tanaka ***@***.***> wrote:
> 
> 
> I'm putting this as an issue instead of edits since I think the merge conflict undid my edits.
> 
> How necessary is the latter part of the sentence? In particular, we need to adhere to blinding so I removed "supervised by author Cook" out to adhere to this.
> 
> "The wages data was used to illustrate exploratory longitudinal data analysis in Ozlem Ilk's PhD thesis supervised by author Cook ***@***.***"
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by emitanaka** [comment]
ok, I'll remove it
