### ISSUE TITLE
Inconsistencies in description for starting work?

### ISSUE THREAD

**Issue by emitanaka** [numbats/yowie-paper#8]
> For `st_work` variable,  we only rename the column names from `new_data_qnames`. This variable is then used to calculate the next variable, `yr_workforce` for each survey round, which is the year of survey (`year`) minus the year of individual start working (`st_work`). Finally, `exp` variable is derived from the number of weeks worked since the last interview indicated as variable started with `WKSWK` in `new_data_qnames`. To obtain the work experience since 1979, we calculate the cumulative value. As the measurement unit is in week, we convert this to year.  

I'm confused with this section as the variable is `stwork` in `data-processing.R` is a data frame and in fact `st_work` is I think referring to `stwork_year`? This seems to be different to `stwork` described in "Tidying employment variables" and `yr_workforce` is named `years_in_workforce`?

**Comment by Dewi-Amaliah** [comment]
Yes, the st_work should be `stwork` in that section. In data-preprocessing.R,  `stwork` =`stwork_year` and `yr_workforce` = `years_in_workforce`. I renamed those in ida.R (before saving it to RDA file) so that the column names are shorter in the package.

**Comment by Dewi-Amaliah** [comment]
I have named it as `stwork` and `yr_wforce` from the beginning in data-preprocessing.R.

**Comment by emitanaka** [comment]
Thanks Dewi! The fix clears it up!
