### ISSUE TITLE
Clarification needed for last paragraph in Section 4?

### ISSUE THREAD

**Issue by emitanaka** [numbats/yowie-paper#9]
"Lastly, the race variable is almost perfectly matched. The `id`'s in the dropouts subset of the refreshed data all correspond to males, which perfectly matches the original subset."

I think this part is referring to the fact that the individuals from the original data (as matched by their IDs) have the same sex and race as original data? If so, I think it would be good to rewrite this one to clarify this.

**Comment by Dewi-Amaliah** [comment]
Yes, you are right. I have rewritten the paragraph.
